name: miniproject
description: "Hostel Complaint and Maintenance App for Hostels"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  google_sign_in: ^6.2.1

  # State Management
  provider: ^6.0.5

  # API Calls (Weather, News, Holidays)
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
